version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'ecg'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      backend:
        aliases:
          - db
  api:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    user: "${UID}:${GID}"
    env_file:
      - .env.docker
    networks:
      backend:
        aliases:
          - api
volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
