site_name: ECG Backend
theme: readthedocs
nav:
  - Home: index.md
  - Installation:
    - Docker: installation/docker.md
  - User Guide:
    - OAuth2 Authentication:
      - Creating Users: auth/create_users.md
      - Login as User: auth/user_login.md
    - API Endpoints:
      - Intro: api.md
      - Upload ECG: ecg_create.md
      - ECG Detail: ecg_detail.md
    - Testing: tests.md