"""Add default for status

Revision ID: 033843a1d580
Revises: 3dc108746467
Create Date: 2024-02-05 13:10:55.687108+01:00

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "033843a1d580"
down_revision: Union[str, None] = "3dc108746467"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
