"""Add DataAnalysis model

Revision ID: 3dc108746467
Revises: abeea6f3fe52
Create Date: 2024-02-05 12:26:06.321304+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3dc108746467"
down_revision: Union[str, None] = "abeea6f3fe52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_analysis",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ecg_id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("finished", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "processing",
                "completed",
                "failed",
                name="analysisstatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecg_id"],
            ["ecg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_analysis_status"), "data_analysis", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_analysis_status"), table_name="data_analysis")
    op.drop_table("data_analysis")
    # ### end Alembic commands ###
