"""Create ECG models

Revision ID: 78dd3a319c0b
Revises: 1b9b576719b8
Create Date: 2024-02-04 02:22:33.935345+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78dd3a319c0b"
down_revision: Union[str, None] = "1b9b576719b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ecg", sa.Column("id", sa.UUID(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "ecg_signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("signal_value", sa.Integer(), nullable=False),
        sa.Column("signal_value_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ecg_signal_date"), "ecg_signal", ["date"], unique=False)
    op.create_index(op.f("ix_ecg_signal_name"), "ecg_signal", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ecg_signal_name"), table_name="ecg_signal")
    op.drop_index(op.f("ix_ecg_signal_date"), table_name="ecg_signal")
    op.drop_table("ecg_signal")
    op.drop_table("ecg")
    # ### end Alembic commands ###
