"""Add cascade delete

Revision ID: abeea6f3fe52
Revises: becb54088400
Create Date: 2024-02-05 00:07:43.827832+01:00

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "abeea6f3fe52"
down_revision: Union[str, None] = "becb54088400"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
