"""Fix ECG id field

Revision ID: becb54088400
Revises: 4e8fcb030194
Create Date: 2024-02-04 22:40:29.712678+01:00

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "becb54088400"
down_revision: Union[str, None] = "4e8fcb030194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
