"""Add FK

Revision ID: c02de0f9d5e4
Revises: 78dd3a319c0b
Create Date: 2024-02-04 02:46:09.046610+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c02de0f9d5e4"
down_revision: Union[str, None] = "78dd3a319c0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ecg", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "ecg", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ecg", type_="foreignkey")
    op.drop_column("ecg", "user_id")
    # ### end Alembic commands ###
