name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Start Docker service
      docker:
        image: docker:20.10.9
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run database first
        run: |
          docker-compose build
          docker-compose up -d db

      - name: Wait for Database
        run: sleep 5

      - name: Run tests
        run: scripts/run_pytest.sh tests

      - name: Stop Docker Compose
        run: docker-compose down
